### ISSUE TITLE
can't create room

### ISSUE THREAD

**Issue by nhathoagn** [KenanDropic/chat-app#2]
[Nest] 18392  - 12/01/2022, 10:57:25 AM   ERROR [WsExceptionsHandler] Cannot read properties of undefined (reading 'push')
TypeError: Cannot read properties of undefined (reading 'push')

async createRoom(roomData: RoomDataDto, creator: UserI): Promise<RoomDto> {
    const user: UserI = {
      ...creator,
    };
    delete user.password;
    delete user.hashedRT;

    const room = {
      ...roomData,
    };
    room.users.push(user);

    return this.repo.save(room);
  }

**Comment by KenanDropic** [comment]
You can't add user who is not registered to the application. While typing in the autocomplete textbox,if the user comes up as an option,you can choose that person. Otherwise it will register that text as empty string,hint it won't be allowed to create a room,giving us a following error.

**Comment by nhathoagn** [comment]
can you show me the postman when adding the message?
